POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "chickenwingz97",
    "name": "Mikey D",
    "password": "ilovechickenwingz"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "pancakeboi1",
    "name": "Chuck E",
    "password": "pancakez4lyfe"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "ilovemcdonalds",
    "name": "Ronald McDonald",
    "password": "abcd12345"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "no",
    "name": "Chuck E",
    "password": "hehexd"
}